apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  replicas: 1 # Makes 1 replica
  selector:
    matchLabels:
      app: sail-user-service
  template:
    metadata:
      labels:
        app: sail-user-service
    spec:
      containers:
      - name: sail-user-service
        image: ignacio6779/sail-user-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  selector:
    app: sail-user-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
