apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  replicas: 1 # Makes 1 replica(s)
  selector:
    matchLabels:
      app: sail-user-service
  template:
    metadata:
      labels:
        app: sail-user-service
    spec:
      containers:
      - name: sail-user-service
        image: ignacio6779/sail-user-service:4bc8796db8f0f1d30edffe012d9e008842d871da
        ports:
        - containerPort: 8080 # This is some kind of a port it seems like. Not sure tho. Know it now, is def standard stuff
        resources:
          limits:
            cpu: "0.2"
            memory: "499Mi"
          requests:
            cpu: "0.1"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  selector:
    app: sail-user-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
