apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  replicas: 1 # Makes 1 replica(s)
  selector:
    matchLabels:
      app: sail-user-service
  template:
    metadata:
      labels:
        app: sail-user-service
    spec:
      containers:
      - name: sail-user-service
        image: ignacio6779/sail-user-service:fa7aa6daa79a3d4f278bc2101ec63242b45be651
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: keycloak-url-secret
              key: keycloakURL
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak-client-id-secret
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-client-secret
              key: client_secret
        resources:
          limits:
            cpu: "0.2"
            memory: "499Mi"
          requests:
            cpu: "0.1"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sail-user-service
  labels:
    app: sail-user-service
spec:
  selector:
    app: sail-user-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
