package config

type Config struct {
	KeycloakURL   string
	KeycloakRealm string
	AdminToken    string
	Port          string
}

func LoadConfig() (*Config, error) {
	return &Config{
		KeycloakURL:   "http://keycloak-route-oscar-dev.apps.inholland.hcs-lab.nl",
		KeycloakRealm: "sail-amsterdam",
		AdminToken:    "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNDJyd1plbXRyWUdabWYzQjE1eklvZlhzQ3FnV0hDUUloMHBDWERURWNVIn0.eyJleHAiOjE3MzY3MjAwOTMsImlhdCI6MTczNjY4NDA5MywianRpIjoiNmJiYTU4MjgtNzE4Ni00ZTQ2LTk5ODgtMDg2OWQ2ZmFmNDA0IiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLXJvdXRlLW9zY2FyLWRldi5hcHBzLmluaG9sbGFuZC5oY3MtbGFiLm5sL3JlYWxtcy9zYWlsLWFtc3RlcmRhbSIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiIzYjZmYTVlZS0zZmJjLTRmZTQtYjFmOS0wMWQ1OGUzODJmMzQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ1c2VyLW1pY3Jvc2VydmljZSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNhaWwtYW1zdGVyZGFtIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtdXNlcnMiLCJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjEwLjEzMC4yLjgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtdXNlci1taWNyb3NlcnZpY2UiLCJjbGllbnRBZGRyZXNzIjoiMTAuMTMwLjIuOCIsImNsaWVudF9pZCI6InVzZXItbWljcm9zZXJ2aWNlIn0.IMLvdRcDb4yQ8ghiiifJAA63yd2rJMFlq-mr5Zkd9JeIYBbfkMG189It_L_heU7KmXyQDFkQFod6bDCyRltyfniKtnttQuLDHECNnGGVWr7rIlKdcMTUSRm_Wl6BDY0isygO1MZ_-MnDyAO1_L2GUcGnw4O8LOioCEnWGcLU7AQ7zAss1Mnv6rq-rOJMz9e6KhK_VNKxWqisG6YcXVxC_eieUguNk3c_hmin06s1ltoncOuOGE8GnhXfQYr3dlKc0DpGy0_u4NzM_ltZpQgkDTcjgxkTq1dGbDCCx6fWAX9EceSqrZWoEL1ZYYAQl7tHqEiPDuTU1Ja4VWjCH7alAA",
		Port:          "8080",
	}, nil
}
