package config

type Config struct {
	KeycloakURL   string
	KeycloakRealm string
	AdminToken    string
	Port          string
}

func LoadConfig() (*Config, error) {
	return &Config{
		KeycloakURL:   "http://keycloak-route-oscar-dev.apps.inholland.hcs-lab.nl",
		KeycloakRealm: "sail-amsterdam",
		AdminToken:    "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNDJyd1plbXRyWUdabWYzQjE1eklvZlhzQ3FnV0hDUUloMHBDWERURWNVIn0.eyJleHAiOjE3MzY4MDcyMjUsImlhdCI6MTczNjc3MTIyNSwianRpIjoiNDg4NTA1MGYtNGUxMS00YTFiLWFkYzMtZTEwNjNlZTgyZDcwIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLXJvdXRlLW9zY2FyLWRldi5hcHBzLmluaG9sbGFuZC5oY3MtbGFiLm5sL3JlYWxtcy9zYWlsLWFtc3RlcmRhbSIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiIzYjZmYTVlZS0zZmJjLTRmZTQtYjFmOS0wMWQ1OGUzODJmMzQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ1c2VyLW1pY3Jvc2VydmljZSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNhaWwtYW1zdGVyZGFtIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtdXNlcnMiLCJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjEwLjEzMC4yLjgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtdXNlci1taWNyb3NlcnZpY2UiLCJjbGllbnRBZGRyZXNzIjoiMTAuMTMwLjIuOCIsImNsaWVudF9pZCI6InVzZXItbWljcm9zZXJ2aWNlIn0.dEl6Z5VDjCu9Jm9EkcIlBM7aN8h_BsHnWhHX7mJr-MisvZr6xBeIcWti72C2KAOQijWxPRKGRJdaGrDuuU9cexzMs6N7ou_4XzUo6VUrfnnNDUgFbIRIlP6asMTzVJGUPpAShJho8SZyoj_gy1Y-Rmufc4GpYK97C4gojTzG_-zF0U1ptDAzorg99MKNTMrU1AUEUetNPYgl_dnQRQKTBzZRJd0LoxBd-XyLywA5A6lNrHYY6k2sJm0wUMkwHWgv0En6P1eql_WjsZYmy3IU6_bcJuYjNHp4SMtE0ETPNLZ1meEUKtkNdmB1E6IdfLkBLDOgYg7UR2PJzU1D8Pp-4A",
		Port:          "8080",
	}, nil
}
