basePath: /
definitions:
  models.User:
    properties:
      firstName:
        type: string
      function:
        type: string
      groupId:
        type: string
      id:
        type: string
      lastName:
        type: string
      roles:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: email.placeholder@gmail.com
    name: API Support
    url: https://www.sail.com
  description: This is the API for the SAIL User Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://swagger.io/terms/
  title: SAIL User Service API
  version: "1.0"
paths:
  /users:
    get:
      description: Retrieves all users from the Keycloak server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Failed to fetch users
          schema:
            type: string
      summary: Get all users
      tags:
      - users
  /users/{id}:
    get:
      description: Retrieves a single user from the Keycloak server by userID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Failed to fetch user
          schema:
            type: string
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
