name: Development CI

on:
  push:
    branches:
      - dev
    paths:
      - '**.go'
      - 'deployment.yaml'
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  # linting:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.20' # Adjust this to your Go version
  
  #     - name: Install linters
  #       run: |
  #         go install golang.org/x/lint/golint@latest # Install golint
  #         go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # Optional: Install golangci-lint
  #         export PATH=$PATH:$(go env GOPATH)/bin
  
  #     - name: Run Golint
  #       run: golint ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -o main ./cmd/main.go
      - name: Test with the Go CLI
        run: go test ./...

  deploy:
      runs-on: ubuntu-latest

      needs: [test]
      steps:
        # Step 1: Check out the code
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install Swag CLI
          run: |
            go get -u github.com/swaggo/swag/cmd/swag
            echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

        - name: Generate Swagger Docs
          run: swag init -g cmd/main.go

        # Step 5: Build and Push Docker Image
        - name: Build and push Docker image
          run: |
            docker build -t ignacio6779/sail-user-service:${{ github.sha }} .
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_ID }} --password-stdin
            docker push ignacio6779/sail-user-service:${{ github.sha }}

        # Step 6: Deploy to OpenShift
        - name: Update deployment.yml
          run: |
            sed -i "s|image: ignacio6779/sail-user-service:.*|image: ignacio6779/sail-user-service:${{ github.sha }}|" deployment.yaml
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add deployment.yaml
            git commit -m "Update deployment.yaml"
            git push
